include:
  - package:flutter_lints/flutter.yaml
  - package:bloc_lint/recommended.yaml

# Custom lint configuration
custom_lint:
  debug: false
  enable_all_lint_rules: false

# Solid lints for enhanced performance rules
analyzer:
  plugins:
    - custom_lint
  errors:
    # Make performance-critical warnings into errors
    avoid_unnecessary_containers: error
    sized_box_for_whitespace: error
    use_key_in_widget_constructors: error
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    prefer_const_constructors_in_immutables: error
    prefer_const_declarations: error
    avoid_init_to_null: error
    unnecessary_null_in_if_null_operators: error
    avoid_catches_without_on_clauses: ignore

linter:
  rules:
    - require_trailing_commas
    # Widget Performance
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    # - avoid_widget_function_calls # is not a standard rule
    
    # Memory Management
    - close_sinks
    - cancel_subscriptions
    - avoid_init_to_null
    - unnecessary_null_in_if_null_operators
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_in_for_each
    
    # List/Collection Performance
    - prefer_collection_literals
    - prefer_spread_collections
    - prefer_for_elements_to_map_fromIterable
    - avoid_function_literals_in_foreach_calls
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_contains
    
    # String Performance
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings
    - unnecessary_string_interpolations
    
    # General Performance
    - avoid_slow_async_io
    - prefer_single_quotes
    - unnecessary_await_in_return
    - avoid_returning_null_for_future
    - unawaited_futures
    - avoid_redundant_argument_values
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - prefer_if_null_operators
    - cascade_invocations
    
    # Build Method Optimization
    - avoid_print
    - avoid_web_libraries_in_flutter
    
    # Custom Performance Rules
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - use_build_context_synchronously
